name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Set AWS Environment Variables
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AMI_ID: ${{ secrets.AMI_ID }}
          INSTANCE_TYPE: ${{ secrets.INSTANCE_TYPE }}
        run: echo "AWS environment variables set"

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AMI_ID: ${{ secrets.AMI_ID }}
          INSTANCE_TYPE: ${{ secrets.INSTANCE_TYPE }}
        run: |
          terraform plan -var="aws_region=$AWS_REGION" \
                         -var="ami_id=$AMI_ID" \
                         -var="instance_type=$INSTANCE_TYPE"

      - name: Apply Terraform
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AMI_ID: ${{ secrets.AMI_ID }}
          INSTANCE_TYPE: ${{ secrets.INSTANCE_TYPE }}
        run: |
          terraform apply -auto-approve -var="aws_region=$AWS_REGION" \
                                       -var="ami_id=$AMI_ID" \
                                       -var="instance_type=$INSTANCE_TYPE"
